s3_prepare_data:
  seed: 42
  n_train: 1000
  n_test: 2000
  remove_offset: true
s5_predict:
  name: calc_correlation
s6_evaluate:
  name: correlation_plot
  plot_function:
    _target_: GPR_MLIP.evaluation.extended_reliablility_diagram
    _partial_: true
  plot_function_kwargs:
    num_bins: 20
    bin_size: null
    min_samples: 50
    num_top_values: null
    max_uncertainty: null
    absolute: false
    max_value: null
    max_value_theory: null
dataset:
  subset:
    subset_function:
      _target_: delta_learning.utils.full
  name: ws22
  molecule_name: o-hbdi
  high_fidelity: ws22
  low_fidelity: XTB
  path: /ws22/o-hbdi.npz
  load_coordinates_function:
    _target_: delta_learning.utils.load_npz
    key: R
    _partial_: true
  load_charges_function:
    _target_: delta_learning.utils.load_npz
    key: Z
    _partial_: true
  load_energies_function:
    _target_: delta_learning.utils.load_scalar_properties_npz
    unit: kcal/mol
    fidelity_keys:
      ws22: E
    _partial_: true
  load_forces_function:
    _target_: delta_learning.utils.load_scalar_properties_npz
    unit: kcal/mol
    fidelity_keys:
      ws22: F
    _partial_: true
model:
  name: single_fidelity_sgdml
  use_forces: true
  init_function:
    _target_: delta_learning.model.sgdml.SingleFidelitySGDML
    fidelity: ws22
    data_conversion_script_path: sGDML/scripts/sgdml_dataset_via_ase.py
    train_kwargs:
      max_memory: null
      max_processes: 1
      use_torch: false
    task_kwargs:
      sig: 20
      lam: 1.0e-10
    charges_function:
      _target_: delta_learning.utils.load_npz
      key: Z
      _partial_: true
    dataset_charges_path: /ws22/o-hbdi.npz
representation:
  name: coulomb
  function:
    _target_: delta_learning.utils.no_representation
